FROM openjdk:11-jdk-slim

LABEL maintainer="howayda.gamal@gmail.com"

FROM maven:3.6-alpine
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy the project source
COPY src src

# Package the application
RUN mvn package -DskipTests
ENV JAR_FILE=target/international-phone-number-0.0.1-SNAPSHOT.jar
RUN mv ${JAR_FILE} /internationalPhoneNumberValidator.jar
ADD ./sample.db .
ENTRYPOINT ["java","-jar","internationalPhoneNumberValidator.jar"]