
FROM openjdk:11

LABEL maintainer="howayda.gamal@gmail.com"

VOLUME /tmp

EXPOSE 8080

ARG JAR_FILE=target/international-phone-number-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} internationalPhoneNumberValidator.jar
ADD ./sample.db .
ENTRYPOINT ["java","-jar","internationalPhoneNumberValidator.jar"]